// Generated by CodiumAI

describe('BadDeleteMatch', () => {

    // Function successfully deletes matching element from both arrays
    it('should delete matching element from both arrays when they have the same length', () => {
        const FirstArray = ['apple', 'banana', 'orange'];
        const SecondArray = ['banana', 'grape', 'orange'];
        const expectedFirstArray = ['apple', 'orange'];
        const expectedSecondArray = ['grape', 'orange'];

        BadDeleteMatch(FirstArray, SecondArray);

        expect(FirstArray).toEqual(expectedFirstArray);
        expect(SecondArray).toEqual(expectedSecondArray);
    });

    // Function throws error if props are empty arrays
    it('should throw an error when props are empty arrays', () => {
        const FirstArray: string[] = [];
        const SecondArray: string[] = [];

        expect(() => {
            BadDeleteMatch(FirstArray, SecondArray);
        }).toThrowError("Arrays are different lengths");
    });
});
