// Generated by CodiumAI

describe('DeleteMatch', () => {

    // Function successfully deletes matching element from both arrays
    it('should delete matching element from both arrays when they have the same length', () => {
        const FirstArray = ['apple', 'banana', 'orange'];
        const SecondArray = ['banana', 'grape', 'orange'];
        DeleteMatch(FirstArray, SecondArray);
        expect(FirstArray).toEqual(['apple', 'orange']);
        expect(SecondArray).toEqual(['grape', 'orange']);
    });

    // First array is empty
    it('should not delete any element when the first array is empty', () => {
        const FirstArray: string[] = [];
        const SecondArray = ['apple', 'banana', 'orange'];
        DeleteMatch(FirstArray, SecondArray);
        expect(FirstArray).toEqual([]);
        expect(SecondArray).toEqual(['apple', 'banana', 'orange']);
    });
});
