// Generated by CodiumAI

describe('AddNumbers', () => {

    // The function adds two positive numbers correctly.
    it('should add two positive numbers correctly', () => {
        const a = 5;
        const b = 10;
        const expected = 15;

        const result = AddNumbers(a, b);

        expect(result).toBe(expected);
    });

    // The function adds two very large numbers (close to the maximum value of a number) correctly.
    it('should add two very large numbers correctly', () => {
        const a = Number.MAX_SAFE_INTEGER - 1;
        const b = Number.MAX_SAFE_INTEGER - 2;
        const expected = Number.MAX_SAFE_INTEGER - 3;

        const result = AddNumbers(a, b);

        expect(result).toBe(expected);
    });
});
