// Generated by CodiumAI

describe('BadAddNumbers', () => {

    // Should add two positive numbers correctly
    it('should add two positive numbers correctly', () => {
        const result = BadAddNumbers(2, 3);
        expect(result).toBe(5);
    });

    // Should add 0 and a positive number correctly
    it('should add 0 and a positive number correctly', () => {
        const result = BadAddNumbers(0, 5);
        expect(result).toBe(5);
    });
});
